/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hcodez.cncapi;

import org.springframework.boot.SpringApplication;

public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
